# Site settings
title: keiches
email: keiches@gmail.com
url: https://keiches.github.io
description: "I have been a front-end, native, and hybrid app developer with more than two decades of experience."
keywords: "JavaScript, TypeScript, ReactJs, ReactNative, VueJs, NodeJs, Flutter, Electron"
skills: "Front End Developer - Web Developer - Native/Hybrid App. Developer"
meta_author: Hansoo Kim

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: keiches
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/keiches
  - title: facebook
    url: http://facebook.com/keiches
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/keiches
  - title: bitbucket
    url: http://bitbucket.org/keiches
  - title: github
    url: http://github.com/keiches
  - title: blogspot
    url: http://pwrwave.blogspot.com

# Postal address (add as many lines as necessary)
address:
  - line: Near Gangnam
  - line: Seoul, Korea

# Credits content
credits: 'This pages built with Freelancer. Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
